[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd ../../ && npm install"]

[phases.build]
cmds = ["cd ../../ && npm run build"]

[start]
cmd = "cd apps/backend && node dist/main"

[build.environment]
NODE_ENV = "production"

[build.args]
NODE_ENV = { default = "production" }
